# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from framework.grpc.clients.ozonmp.act_device_api.v1 import (
    act_device_api_pb2 as ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2,
)


class ActDeviceApiServiceStub(object):
    """ActDeviceApiService - Service for working with templates"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDeviceV1 = channel.unary_unary(
            "/ozonmp.act_device_api.v1.ActDeviceApiService/CreateDeviceV1",
            request_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.CreateDeviceV1Request.SerializeToString,
            response_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.CreateDeviceV1Response.FromString,
        )
        self.DescribeDeviceV1 = channel.unary_unary(
            "/ozonmp.act_device_api.v1.ActDeviceApiService/DescribeDeviceV1",
            request_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.DescribeDeviceV1Request.SerializeToString,
            response_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.DescribeDeviceV1Response.FromString,
        )
        self.ListDevicesV1 = channel.unary_unary(
            "/ozonmp.act_device_api.v1.ActDeviceApiService/ListDevicesV1",
            request_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.ListDevicesV1Request.SerializeToString,
            response_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.ListDevicesV1Response.FromString,
        )
        self.UpdateDeviceV1 = channel.unary_unary(
            "/ozonmp.act_device_api.v1.ActDeviceApiService/UpdateDeviceV1",
            request_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.UpdateDeviceV1Request.SerializeToString,
            response_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.UpdateDeviceV1Response.FromString,
        )
        self.RemoveDeviceV1 = channel.unary_unary(
            "/ozonmp.act_device_api.v1.ActDeviceApiService/RemoveDeviceV1",
            request_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.RemoveDeviceV1Request.SerializeToString,
            response_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.RemoveDeviceV1Response.FromString,
        )


class ActDeviceApiServiceServicer(object):
    """ActDeviceApiService - Service for working with templates"""

    def CreateDeviceV1(self, request, context):
        """CreateDeviceV1 - Create a device"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DescribeDeviceV1(self, request, context):
        """DescribeDeviceV1 - Describe a device"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListDevicesV1(self, request, context):
        """ListDevicesV1 - List of devices"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateDeviceV1(self, request, context):
        """UpdateDeviceV1 - Update a device"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveDeviceV1(self, request, context):
        """RemoveDeviceV1 - Remove a device"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ActDeviceApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateDeviceV1": grpc.unary_unary_rpc_method_handler(
            servicer.CreateDeviceV1,
            request_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.CreateDeviceV1Request.FromString,
            response_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.CreateDeviceV1Response.SerializeToString,
        ),
        "DescribeDeviceV1": grpc.unary_unary_rpc_method_handler(
            servicer.DescribeDeviceV1,
            request_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.DescribeDeviceV1Request.FromString,
            response_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.DescribeDeviceV1Response.SerializeToString,
        ),
        "ListDevicesV1": grpc.unary_unary_rpc_method_handler(
            servicer.ListDevicesV1,
            request_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.ListDevicesV1Request.FromString,
            response_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.ListDevicesV1Response.SerializeToString,
        ),
        "UpdateDeviceV1": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateDeviceV1,
            request_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.UpdateDeviceV1Request.FromString,
            response_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.UpdateDeviceV1Response.SerializeToString,
        ),
        "RemoveDeviceV1": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveDeviceV1,
            request_deserializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.RemoveDeviceV1Request.FromString,
            response_serializer=ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.RemoveDeviceV1Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ozonmp.act_device_api.v1.ActDeviceApiService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ActDeviceApiService(object):
    """ActDeviceApiService - Service for working with templates"""

    @staticmethod
    def CreateDeviceV1(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ozonmp.act_device_api.v1.ActDeviceApiService/CreateDeviceV1",
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.CreateDeviceV1Request.SerializeToString,
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.CreateDeviceV1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DescribeDeviceV1(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ozonmp.act_device_api.v1.ActDeviceApiService/DescribeDeviceV1",
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.DescribeDeviceV1Request.SerializeToString,
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.DescribeDeviceV1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ListDevicesV1(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ozonmp.act_device_api.v1.ActDeviceApiService/ListDevicesV1",
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.ListDevicesV1Request.SerializeToString,
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.ListDevicesV1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateDeviceV1(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ozonmp.act_device_api.v1.ActDeviceApiService/UpdateDeviceV1",
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.UpdateDeviceV1Request.SerializeToString,
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.UpdateDeviceV1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RemoveDeviceV1(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ozonmp.act_device_api.v1.ActDeviceApiService/RemoveDeviceV1",
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.RemoveDeviceV1Request.SerializeToString,
            ozonmp_dot_act__device__api_dot_v1_dot_act__device__api__pb2.RemoveDeviceV1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
