"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Device(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    PLATFORM_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    ENTERED_AT_FIELD_NUMBER: builtins.int
    id: builtins.int
    platform: typing.Text
    user_id: builtins.int
    @property
    def entered_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        platform: typing.Text = ...,
        user_id: builtins.int = ...,
        entered_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["entered_at", b"entered_at"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "entered_at",
            b"entered_at",
            "id",
            b"id",
            "platform",
            b"platform",
            "user_id",
            b"user_id",
        ],
    ) -> None: ...

global___Device = Device

class CreateDeviceV1Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PLATFORM_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    platform: typing.Text
    user_id: builtins.int
    def __init__(
        self,
        *,
        platform: typing.Text = ...,
        user_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "platform", b"platform", "user_id", b"user_id"
        ],
    ) -> None: ...

global___CreateDeviceV1Request = CreateDeviceV1Request

class CreateDeviceV1Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEVICE_ID_FIELD_NUMBER: builtins.int
    device_id: builtins.int
    def __init__(
        self,
        *,
        device_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["device_id", b"device_id"]
    ) -> None: ...

global___CreateDeviceV1Response = CreateDeviceV1Response

class DescribeDeviceV1Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEVICE_ID_FIELD_NUMBER: builtins.int
    device_id: builtins.int
    def __init__(
        self,
        *,
        device_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["device_id", b"device_id"]
    ) -> None: ...

global___DescribeDeviceV1Request = DescribeDeviceV1Request

class DescribeDeviceV1Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> global___Device: ...
    def __init__(
        self,
        *,
        value: typing.Optional[global___Device] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["value", b"value"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["value", b"value"]
    ) -> None: ...

global___DescribeDeviceV1Response = DescribeDeviceV1Response

class ListDevicesV1Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PAGE_FIELD_NUMBER: builtins.int
    PER_PAGE_FIELD_NUMBER: builtins.int
    page: builtins.int
    per_page: builtins.int
    def __init__(
        self,
        *,
        page: builtins.int = ...,
        per_page: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal["page", b"page", "per_page", b"per_page"],
    ) -> None: ...

global___ListDevicesV1Request = ListDevicesV1Request

class ListDevicesV1Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Device
    ]: ...
    def __init__(
        self,
        *,
        items: typing.Optional[typing.Iterable[global___Device]] = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["items", b"items"]
    ) -> None: ...

global___ListDevicesV1Response = ListDevicesV1Response

class UpdateDeviceV1Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEVICE_ID_FIELD_NUMBER: builtins.int
    PLATFORM_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    device_id: builtins.int
    platform: typing.Text
    user_id: builtins.int
    def __init__(
        self,
        *,
        device_id: builtins.int = ...,
        platform: typing.Text = ...,
        user_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "device_id", b"device_id", "platform", b"platform", "user_id", b"user_id"
        ],
    ) -> None: ...

global___UpdateDeviceV1Request = UpdateDeviceV1Request

class UpdateDeviceV1Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["success", b"success"]
    ) -> None: ...

global___UpdateDeviceV1Response = UpdateDeviceV1Response

class RemoveDeviceV1Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEVICE_ID_FIELD_NUMBER: builtins.int
    device_id: builtins.int
    def __init__(
        self,
        *,
        device_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["device_id", b"device_id"]
    ) -> None: ...

global___RemoveDeviceV1Request = RemoveDeviceV1Request

class RemoveDeviceV1Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FOUND_FIELD_NUMBER: builtins.int
    found: builtins.bool
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["found", b"found"]
    ) -> None: ...

global___RemoveDeviceV1Response = RemoveDeviceV1Response

class DeviceEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    DEVICE_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    id: builtins.int
    device_id: builtins.int
    type: builtins.int
    status: builtins.int
    @property
    def payload(self) -> global___Device: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        device_id: builtins.int = ...,
        type: builtins.int = ...,
        status: builtins.int = ...,
        payload: typing.Optional[global___Device] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["payload", b"payload"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "device_id",
            b"device_id",
            "id",
            b"id",
            "payload",
            b"payload",
            "status",
            b"status",
            "type",
            b"type",
        ],
    ) -> None: ...

global___DeviceEvent = DeviceEvent
